name: "Azure Blob Storage Upload"
author: "Matthew Fisher <matt.fisher@microsoft.com>"
description: "Uploads assets to Azure Blob Storage"
branding:
  icon: "box"
  color: "green"
inputs:
  connection_string:
    description: "The connection string for the storage account"
    required: true
  source:
    description: "The name of the directory you want to upload"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"